stages:
  - build
#  - test
#  - package

image: mcr.microsoft.com/dotnet/sdk:latest

#variables:
#  DOTNET_VERSION: "6.0"

# The Build stage
build:
  stage: build
#  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
  script:
    - echo "Restoring dependencies..."
    - dotnet restore
    - echo "Building the project..."
    - dotnet build --configuration Release --no-restore
  artifacts:
    paths:
      - bin/Release/
    expire_in: 1 week

# The Test stage
#test:
#  stage: test
#  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
#  script:
#    - echo "Running tests..."
#    - dotnet test --configuration Release --logger:trx --results-directory TestResults --no-build --verbosity normal
#  dependencies:
#    - build
#  artifacts:
#    reports:
#      junit: TestResults/*.trx
#    paths:
#      - TestResults/
#    expire_in: 1 week

# The Package stage
#package:
#  stage: package
#  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
#  script:
#    - echo "Packing the project..."
#    - dotnet pack --configuration Release --output ./nupkg
#  artifacts:
#    paths:
#      - nupkg/
#    expire_in: 1 week

# The Publish stage (commented out for future use)
# publish:
#   stage: publish
#   image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
#   script:
#     - echo "Publishing the package to NuGet.org..."
#     - dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
#   only:
#     - main
