
stages:
  - build
  - test
  - analysis
  - package
  - deploy

variables:
  DOTNET_VERSION: latest

default:
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION


# The Build stage
build:
  stage: build
  script:
    - echo "Restoring dependencies..."
    - dotnet restore
    - echo "Building the project..."
    - dotnet build --configuration Release --no-restore
    - echo "Build succeeded."
  artifacts:
    paths:
      - bin/Release/
    expire_in: 1 week
    when: on_success


# The Test stage
#test:
#  stage: test
#  script:
#    - echo "Running tests..."
#    - dotnet test --configuration Release --logger "trx;LogFileName=$TEST_RESULTS_DIR/test_results.trx" --verbosity normal --results-directory TestResults
#    - echo "test stage completed"
#  dependencies:
#    - build
#  artifacts:
#    reports:
#      junit: TestResults/*.trx
#    paths:
#      - TestResults/
#    expire_in: 1 week

test:
  stage: test
  script:
    - echo "Starting tests stage..."
    - dotnet add package coverlet.msbuild
    - dotnet test --configuration Release /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/
#    - ls -la coverage
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - export PATH="$PATH:/root/.dotnet/tools"
    - reportgenerator "-reports:./coverage/coverage.cobertura.xml" "-targetdir:coverage-report" 
#    - ls -la coverage-report
    - echo "Test stage completed."
  dependencies:
    - build
  artifacts:
    paths:
      - coverage-report/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.cobertura.xml
#    expire_in: 1 hour
  coverage: '/^\s*Total\s*:\s*\d+\s*\/\s*\d+\s*\((\d+\.\d+)%\)/'



# Code Analysis stage
analysis:
  stage: analysis
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY
                    -Dsonar.sources=.
                    -Dsonar.exclusions=_site
                    -Dsonar.host.url=$SONAR_HOST_URL
                    -Dsonar.login=$SONAR_LOGIN
  allow_failure: false
  dependencies:
    - build
  only:
    - main


# The Package stage
package:
  stage: package
  script:
    - echo "Packing the project..."
    - dotnet pack --configuration Release --output nupkg
    - echo "Nuget package was created successfully."
  dependencies:
    - analysis
    - build
  when: manual
  artifacts:
    paths:
      - nupkg/
#    expire_in: 1 hour
    when: on_success


# Deploy gitlab page
pages:
  stage: deploy
  needs: ["package"]
  image: alpine:latest
  script:
    - echo "start setup of website ..."
    - rm -r public
    - cp -r ./_site ./public
  artifacts:
    paths:
      - public