stages:
  - build
#  - test
  - analysis
  - package
  - publish

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

include:
  - local: '/.gitlab-ci-ci.yml'
  - local: '/.gitlab-ci-cd.yml'


